# Generated by Django 5.2.7 on 2025-10-30 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Surah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'سورة',
                'verbose_name_plural': 'السور',
            },
        ),
        migrations.CreateModel(
            name='Ayah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('normalized', models.TextField(blank=True, db_index=True, default='')),
                ('surah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ayahs', to='quran.surah')),
            ],
            options={
                'ordering': ['number'],
                'unique_together': {('surah', 'number')},
            },
        ),
    ]
