# Generated by Django 5.2.7 on 2025-11-17 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ayah',
            name='normalized',
            field=models.TextField(blank=True, db_index=True, default='', help_text='نص مُطهَّر للبحث (بدون تشكيل/رموز).'),
        ),
        migrations.CreateModel(
            name='TafseerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surah', models.PositiveSmallIntegerField(help_text='رقم السورة (1-114)')),
                ('ayah', models.PositiveSmallIntegerField(help_text='رقم الآية داخل السورة')),
                ('lang', models.CharField(default='ar', help_text='رمز اللغة مثل ar أو en', max_length=5)),
                ('source', models.CharField(default='sadi', help_text='اسم مصدر التفسير (مثلاً: السعدي).', max_length=50)),
                ('text_short', models.TextField(help_text='نص التفسير المختصر للآية.')),
            ],
            options={
                'verbose_name': 'تفسير مختصر',
                'verbose_name_plural': 'تفاسير مختصرة',
                'indexes': [models.Index(fields=['surah', 'ayah'], name='quran_tafse_surah_134ca2_idx')],
                'unique_together': {('surah', 'ayah', 'lang', 'source')},
            },
        ),
    ]
